parser: '@typescript-eslint/parser'
env:
  es6: true
  node: true
plugins:
  - '@typescript-eslint'
  - standard
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - standard
parserOptions:
  sourceType: module
  tsconfigRootDir: '.'
  project: ./tsconfig.json
rules:
  '@typescript-eslint/no-misused-promises': off
  indent: [error, 4]
